language: node_js

cache:
  directories:
    - $HOME/.npm

node_js:
  - 8
  - 10

jobs:
  include:
    - stage: release
      node_js: 10
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
