language: node_js

cache:
  directories:
    - $HOME/.npm

node_js:
  - 10
  - 12

branches:
  only:
    - master
    - /v\d+[.]\d+[.]\d+/

jobs:
  include:
    - if: branch = master
      stage: release
      node_js: 10
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
